### ISSUE TITLE
Problem with relationships objects

### ISSUE THREAD

**Issue by openkwaky** [xamoom/Morpheus#1]
Hi,

thank you for your lib, but it still remains a lot of problems on RelationShips mapping object.
For example, here is my data returned :

``` json
{
  "links": {
    "self": "/stations/64/steps?filter%5Bdepth%5D=3&include=track&page%5Blimit%5D=1",
    "next": "/stations/64/steps?filter%5Bdepth%5D=3&include=track&page%5Blimit%5D=1&page%5Boffset%5D=1"
  },
  "data": [
    {
      "id": "b6228a75-0d2b-4884-b8f8-d2e6756f82ad",
      "type": "steps",
      "attributes": {
        "title": "THE BOSTON WRANGLER - BO/THE THOMAS CROWN AFFAIR",
        "startTime": 1448258477,
        "endTime": 1448258640,
        "depth": 3,
        "radioMetadata": {
          "id": "201511230701170006402345652abb47aef32.50399443"
        }
      },
      "relationships": {
        "station": {
          "data": {
            "type": "stations",
            "id": 64
          }
        },
        "track": {
          "data": {
            "type": "tracks",
            "id": "21b7f162-4bf3-48b5-9c98-c0462bcf7819"
          }
        }
      }
    }
  ],
  "included": [
    {
      "id": "21b7f162-4bf3-48b5-9c98-c0462bcf7819",
      "type": "tracks",
      "attributes": {
        "title": "THE BOSTON WRANGLER",
        "release": {
          "title": "THE THOMAS CROWN AFFAIR SOUNDTRACK",
          "year": 1968
        },
        "artists": [
          {
            "name": "BO/L AFFAIRE THOMAS CROWN"
          }
        ],
        "label": {
          "name": "RYKO"
        },
        "images": [],
        "videos": [
          {
            "provider": "Youtube",
            "url": "https://www.youtube.com/watch?v=nsseRXOWeNA",
            "images": [
              {
                "url": "https://i.ytimg.com/vi/nsseRXOWeNA/hqdefault.jpg"
              }
            ]
          }
        ],
        "affiliates": []
      }
    }
  ]
}
```

I have "stations" and "tracks" types in Relationship. But it's a pain to get it deserialized in basic Java classes.
For the moment, I just succeeded to make a class Track full of JSONObject and HashMap instead of having a clean model class

``` java
public class Track extends Resource{
    private String title;
    private HashMap<String, String> release;
    private ArrayList<JSONObject> artists;
    private HashMap<String, String> label;
    private ArrayList<JSONObject> images;
    private ArrayList<JSONObject> videos;
    private ArrayList<JSONObject> affiliates;
 ...
```

instead of for example :

``` java
public class Track extends Resource{
    private String title;
    private Release release;
    private List<Artist> artists;
    private Label label;
    private List<Image> images;
    private List<Video> videos;
    private List<Affiliate> affiliates;
...
```

Do you plan to improve your lib to make it work more like Gson ?

**Comment by DenisMondon** [comment]
Hi!

Great lib! But I have the same problem... :'(
It's really difficult to use as it in my project: I just want to have "real" classes like **Image** instead of **JSONObject**!

Thanks a lot for your answer.

**Comment by raphaelseher** [comment]
Hey guys,
i see what you mean. I did not thought about such structures inside of the "attributes" when developing Morpheus.

ATM you can only subclass AttributeMapper.java and deserialize these objects by your own.
But I will try to find a good solution for you problem until next week.

In my mind there are two things: 
- Extending the AttributeMapper.java with the ability to parse custom objects
- Refactor Morpheus to work with Gson/Jackson, so this problem will also go away

I will keep you updated.

**Comment by openkwaky** [comment]
Thank you for your answer. Indeed, a code using Gson would be great.
What about using an interface for AttributeMapper instead of a class directly to allow lib users to implement their own AttributeMapper without changing your lib ?

**Comment by raphaelseher** [comment]
Guys i made a simple change to the AttributeMapper.java and pushed it to master. Can you download and try out, if this solution would work for you?

**Comment by openkwaky** [comment]
I'll give it a try soon, thanx

**Comment by openkwaky** [comment]
Hi Raphael,

it works great, cool :)
