### ISSUE TITLE
List<String> not parsed correctly

### ISSUE THREAD

**Issue by emanuelthedude** [xamoom/Morpheus#12]
Arrays of Strings are not parsed and remain null. Everything is fine with very simple Strings like ["12", "34"] but if the Strings contain ":" or " " like ["12 34", "12:34"] the result remains null. 

Tested it with version 0.4.3

**Comment by raphaelseher** [comment]
Hey, thanks for the Report. I will try to fix it this weekend.

**Comment by xamoom-raphael** [comment]
Should be fixed in #13
