### ISSUE TITLE
Mapping Relationships

### ISSUE THREAD

**Issue by darrelRayen** [xamoom/Morpheus#18]
Hi,
I tried to map a relationship using the above library. it actually returning a null.  But the attributes are mapped without any issues. its just the relationship. Can you help me with the issue ?

**Comment by raphaelseher** [comment]
Hey. 
Can you provide me a JSON so I can reproduce it and help you.

**Comment by darrelRayen** [comment]
Hi..sure..
{
  "data": [
    {
      "type": "accounts",
      "id": "134564648asdad5614da",
      "attributes": {
        "name": "test1",
        "domain": "www.test.com"
      },
      "relationships": {
        "images": {
          "data": []
        }
      }
    },
    {
      "type": "accounts",
      "id": "jdudif6364748433",
      "attributes": {
        "name": "test2",
        "domain": "www.test.com"
      },
      "relationships": {
        "images": {
          "data": [
            {
              "id": "asdasdasdasdasd23432",
              "type": "images",
              "meta": {
                "image": "www.test.com",
                "type": "logo",
                "removable": true
              }
            }
          ]
        }
      }
    },
    {
      "type": "accounts",
      "id": "jdudif6364748433asdas",
      "attributes": {
        "name": "Test3",
        "domain": "www.test.com"
      },
      "relationships": {
        "images": {
          "data": [
            {
              "id": "21323213asdasddasds",
              "type": "images",
              "meta": {
                "image": "www.test.com",
                "type": "background",
                "removable": true
              }
            },
            {
              "id": "asdasdasdasd232312323",
              "type": "images",
              "meta": {
                "image": "www.test.com",
                "type": "logo",
                "removable": true
              }
            }
          ]
        }
      }
    }
  ],
  "meta": {
    "count": 3
  }
`}```

**Comment by xamoom-raphael** [comment]
So, I just tested it and it worked. 

I did:

1. Create `Account.class`
```
public class Account extends Resource {
  @Relationship("images")
  private List<Images> images;
}
```

2. Create `Images.class`
```
public class Images extends Resource {
 // uses only meta
}
```

3. Register both and parsed

```
    Morpheus morpheus = new Morpheus();
    Deserializer.registerResourceClass("accounts", Account.class);
    Deserializer.registerResourceClass("images", Images.class);

    try {
      JsonApiObject jsonApiObject = morpheus.parse(jsonString);
       Log.v(TAG, "Test: " + jsonApiObject);
    } catch (Exception e) {
      e.printStackTrace();
    }
```

Resulting this jsonApiObject:
![screen shot 2018-01-08 at 10 59 32](https://user-images.githubusercontent.com/10596108/34666126-1237e346-f463-11e7-9eed-f6a14b682af6.png)


Can you check, If you setup something wrong? 
(Or maybe I did understand your question wrong, then please clarify)

**Comment by darrelRayen** [comment]
You are correct. I did not map it as a list. Thats where I went wrong. Thanks on that. But how can I get the values under the "meta" tag in images ArrayList. because that is what I actually need. Can you help ?

**Comment by xamoom-raphael** [comment]
You can try it like this:
```
List<Resource> accounts = new ArrayList<>();
accounts.addAll(jsonApiObject.getResources());

for (Resource account : accounts) {
  List<Images> images = ((Account) account).getImages();
  Log.v(TAG, account.getId());
    for (Images image : images) {
      Log.v(TAG, image.getMeta().get("image").toString());
    }
}
```

I just realized, there is no convienient way to convert the Resources to the custom Object. Have to make it better in the future.

**Comment by darrelRayen** [comment]
That worked !. Thanks for helping me out on this !

**Comment by xamoom-raphael** [comment]
Glad I could help. 
If you have other problems, issues or feature-requests please create a new issue.
