### ISSUE TITLE
mapping class to <included> Array

### ISSUE THREAD

**Issue by darrelRayen** [xamoom/Morpheus#19]
Hi I have the following issue. in my json response I have a arrayList called included. I am trying to map my object to the objects in the ArrayList. The object is getting mapped (the id is there) but the attributes are not getting mapped though. Can you help on this ?

**Comment by xamoom-raphael** [comment]
Can you provide me an example json to reproduce this behavior?

**Comment by darrelRayen** [comment]
Sure !
{
  "data": [
    {
      "type": "students",
      "id": "1WKXBU",
      "attributes": {
        "firstName": "test@gmail.com",
        "lastName": "",
        "address": "",
        "registeredAt": 1517923748110
      },
      "relationships": {
        "application": {
          "data": {
            "type": "applications",
            "id": "IH2QYE"
          }
        }
      }
    },
    {
      "type": "students",
      "id": "Q5W3GW",
      "attributes": {
        "firstName": "test@gmail.com",
        "lastName": "",
        "address": "",
        "registeredAt": 1517923748110
      },
      "relationships": {
        "application": {
          "data": {
            "type": "applications",
            "id": "DP9SYT"
          }
        }
      }
    },
    {
      "type": "students",
      "id": "AUKNPN",
      "attributes": {
        "firstName": "test@gmail.com",
        "lastName": "",
        "address": "",
        "registeredAt": 1517923748110
      },
      "relationships": {
        "application": {
          "data": {
            "type": "applications",
            "id": "56U5C1"
          }
        }
      }
    },
    {
      "type": "students",
      "id": "OEOTMB",
      "attributes": {
        "firstName": "test@gmail.com",
        "lastName": "",
        "address": "",
        "registeredAt": 1517826488551
      },
      "relationships": {
        "application": {
          "data": {
            "type": "applications",
            "id": "L3MI5I"
          }
        }
      }
    }
  ],
  "included": [
    {
      "type": "applications",
      "id": "IH2QYE",
      "attributes": {
        "appliedAt": 1517920883869,
        "status": "in-progress",
        "matchingScore": 0
      }
    },
    {
      "type": "applications",
      "id": "DP9SYT",
      "attributes": {
        "appliedAt": 1517920883869,
        "status": "in-progress",
        "matchingScore": 0
      }
    },
    {
      "type": "applications",
      "id": "56U5C1",
      "attributes": {
        "appliedAt": 1517920883869,
        "status": "new",
        "matchingScore": 2.129279788309624
      }
    },
    {
      "type": "applications",
      "id": "L3MI5I",
      "attributes": {
        "appliedAt": 1517920883869,
        "status": "in-progress",
        "matchingScore": 37.31343283582089
      }
    }
  ]
}

For some reason I cannot map the attributes of "applications". But I get the object though

**Comment by xamoom-raphael** [comment]
Thanks! Will check this in a moment.

**Comment by darrelRayen** [comment]
Sure ! Thanks in advance !

**Comment by xamoom-raphael** [comment]
I tried your json out with these classes:

Student.java
```java
public class Student extends Resource {

  @SerializedName("firstName")
  public String firstName;

  @SerializedName("registeredAt")
  public long registeredTimestamp;

  @Relationship("application")
  public Application application;

  @Override
  public String toString() {
    return "FirstName: " + firstName + "\nApplication: " + application;
  }
}
```

Application.java
```java
public class Application extends Resource {

  @SerializedName("status")
  public String status;

  @SerializedName("matchingScore")
  public int matchingScore;

  @SerializedName("appliedAt")
  public long appliedTimestamp;
}
```

MainActivity.java
```java
Deserializer.registerResourceClass("students", Student.class);
    Deserializer.registerResourceClass("applications", Application.class);
    Morpheus morpheus = new Morpheus();

    try {
      JsonApiObject object = morpheus.parse(getJsonString());
      for (Resource resource : object.getResources()) {
        Student student = (Student) resource;
        Log.d("Test", "" +
            "StudentName: " + student.firstName + "\n" +
            "StudentRegistered: " + student.registeredTimestamp + "\n" +
            "Application Status: " + student.application.status + "\n" +
            "Application Score: " + student.application.matchingScore + "\n" +
            "Application AppliedTS: " + student.application.appliedTimestamp);
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
```

The log will output your data of the student and the application.
Can you check If you forget some configuration?

**Comment by darrelRayen** [comment]
I have used the exact configuration. But I dont get the attributes though.Please check this 
![screenshot from 2018-02-08 16-58-48](https://user-images.githubusercontent.com/29795793/35970740-7be1518c-0cf1-11e8-981b-b5dabb828c37.png)

**Comment by xamoom-raphael** [comment]
Do you have an mismatch between the datatype in the json and the type of your variable?
If there is a e.g. a Number in the json and you want to match it to String, then it will fail and all values will have a null value.

**Comment by darrelRayen** [comment]
This is the class I have created
![screenshot from 2018-02-08 23-02-29](https://user-images.githubusercontent.com/29795793/35988363-3612b140-0d24-11e8-9d88-1e0ddd4519e4.png)

**Comment by darrelRayen** [comment]
Hi.. I actually figured out the issue. It is the data types. Thanks for helping me out
![screenshot from 2018-02-09 11-56-10](https://user-images.githubusercontent.com/29795793/36014515-4f83a33e-0d90-11e8-8b1f-be007d83b08c.png)
