### ISSUE TITLE
Please remove logging unless a log flag is set with a particular log level and absolutely remove all e.printStackTraces() from the code 

### ISSUE THREAD

**Issue by jlmalone** [xamoom/Morpheus#8]
I am getting so many printstacktraces that it actually breaks logcat entirely and subsequent app messages cannot be logged.

**Comment by xamoom-raphael** [comment]
Jep. I will change this today.

**Comment by jlmalone** [comment]
Much appreciated!

**Comment by xamoom-raphael** [comment]
Solved in https://github.com/xamoom/Morpheus/commit/44e0353ff24e4a38ce2133f3ea5428a4fc08b9c9
